#!/bin/bash

echo ""
if [ -f ./waves/tb_run ]; then
   rm ./waves/tb_run
fi

iverilog \
   -I ./rtl/ \
   -g2001 \
   -o ./waves/tb_run \
   ./rtl/*.v

if [ -f ./waves/tb_run ]; then
   vvp ./waves/tb_run
fi
echo ""
