//
// Milkyway Hierarchical Verilog Dump:
// Generated on 02/03/2014 at 15:26:30
// Design Generated by Cell Based Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :mw_orca_lib
// Cell Name    :cpu_floorplan
// Hierarchy delimiter:'/'
// Write Command : write_verilog ../../backend/dgen/pnr/signoff/cpu_signoff.v -pg  
//	-no_physical_only_cells
//


module ram_port (drive_enable , port_write , drive_value , current_value , 
    port_value , current_addr , port_addr , vdd , gnd );
input  drive_enable ;
output port_write ;
input  [7:0] drive_value ;
output [7:0] current_value ;
inout  [7:0] port_value ;
input  [7:0] current_addr ;
output [7:0] port_addr ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


assign current_value[7] = port_value[7] ;
assign current_value[6] = port_value[6] ;
assign current_value[5] = port_value[5] ;
assign current_value[4] = port_value[4] ;
assign current_value[3] = port_value[3] ;
assign current_value[2] = port_value[2] ;
assign current_value[1] = port_value[1] ;
assign current_value[0] = port_value[0] ;
assign port_addr[7] = current_addr[7] ;
assign port_addr[6] = current_addr[6] ;
assign port_addr[5] = current_addr[5] ;
assign port_addr[4] = current_addr[4] ;
assign port_addr[3] = current_addr[3] ;
assign port_addr[2] = current_addr[2] ;
assign port_addr[1] = current_addr[1] ;
assign port_addr[0] = current_addr[0] ;
INVX0 U2 (.ZN ( n1 ) , .VDD ( vdd ) , .INP ( drive_enable ) , .VSS ( gnd ) ) ;
AO21X1 U6 (.VDD ( vdd ) , .IN2 ( drive_value[5] ) , .IN1 ( drive_enable ) 
    , .IN3 ( gnd ) , .Q ( port_value[5] ) , .VSS ( gnd ) ) ;
AO21X1 U5 (.VDD ( vdd ) , .IN2 ( drive_value[6] ) , .IN1 ( drive_enable ) 
    , .IN3 ( gnd ) , .Q ( port_value[6] ) , .VSS ( gnd ) ) ;
AO21X1 U4 (.VDD ( vdd ) , .IN2 ( drive_value[7] ) , .IN1 ( drive_enable ) 
    , .IN3 ( gnd ) , .Q ( port_value[7] ) , .VSS ( gnd ) ) ;
AO22X1 U10 (.IN1 ( n1 ) , .VSS ( gnd ) , .IN3 ( drive_enable ) , .VDD ( vdd ) 
    , .IN2 ( gnd ) , .Q ( port_value[1] ) , .IN4 ( drive_value[1] ) ) ;
TNBUFFX1 port_value_tri_0_ (.ENB ( drive_enable ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .INP ( drive_value[0] ) , .Z ( port_value[0] ) ) ;
AO21X1 U9 (.VDD ( vdd ) , .IN2 ( drive_value[2] ) , .IN1 ( drive_enable ) 
    , .IN3 ( gnd ) , .Q ( port_value[2] ) , .VSS ( gnd ) ) ;
AO21X1 U8 (.VDD ( vdd ) , .IN2 ( drive_value[3] ) , .IN1 ( drive_enable ) 
    , .IN3 ( gnd ) , .Q ( port_value[3] ) , .VSS ( gnd ) ) ;
AO21X1 U7 (.VDD ( vdd ) , .IN2 ( drive_value[4] ) , .IN1 ( drive_enable ) 
    , .IN3 ( gnd ) , .Q ( port_value[4] ) , .VSS ( gnd ) ) ;
endmodule




module alu (operation , a_i , b_i , psr , result , apsr , vdd , gnd );
input  [3:0] operation ;
input  [7:0] a_i ;
input  [7:0] b_i ;
input  [2:0] psr ;
output [7:0] result ;
output [2:0] apsr ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


NOR3X0 U204 (.IN2 ( operation[1] ) , .QN ( n196 ) , .VSS ( gnd ) , .VDD ( vdd ) 
    , .IN1 ( operation[2] ) , .IN3 ( operation[0] ) ) ;
INVX0 U14 (.ZN ( n23 ) , .VDD ( vdd ) , .INP ( operation[3] ) , .VSS ( gnd ) ) ;
AOI22X1 U58 (.IN3 ( n196 ) , .IN4 ( N72 ) , .IN2 ( n77 ) , .IN1 ( n176 ) 
    , .VSS ( gnd ) , .QN ( n180 ) , .VDD ( vdd ) ) ;
OR2X1 U5 (.VDD ( vdd ) , .IN2 ( n78 ) , .IN1 ( n37 ) , .VSS ( gnd ) , .Q ( n26 ) ) ;
NAND2X1 U4 (.IN2 ( n23 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n142 ) 
    , .QN ( n25 ) ) ;
AND3X1 U2 (.IN2 ( operation[0] ) , .IN1 ( operation[2] ) , .IN3 ( n110 ) 
    , .Q ( n24 ) , .VDD ( vdd ) , .VSS ( gnd ) ) ;
NAND2X1 U55 (.IN2 ( n23 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n68 ) 
    , .QN ( n70 ) ) ;
NAND2X0 U54 (.VDD ( vdd ) , .IN1 ( n202 ) , .VSS ( gnd ) , .IN2 ( N121 ) 
    , .QN ( n130 ) ) ;
INVX0 U51 (.ZN ( n17 ) , .VDD ( vdd ) , .INP ( operation[0] ) , .VSS ( gnd ) ) ;
OR2X1 U50 (.VDD ( vdd ) , .IN2 ( operation[0] ) , .IN1 ( n110 ) , .VSS ( gnd ) 
    , .Q ( n97 ) ) ;
NAND3X0 U48 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n62 ) , .IN3 ( n17 ) 
    , .IN2 ( operation[2] ) , .IN1 ( operation[1] ) ) ;
INVX0 U47 (.ZN ( n56 ) , .VDD ( vdd ) , .INP ( a_i[0] ) , .VSS ( gnd ) ) ;
NAND2X0 U46 (.VDD ( vdd ) , .IN1 ( n59 ) , .VSS ( gnd ) , .IN2 ( n60 ) 
    , .QN ( n50 ) ) ;
INVX0 U45 (.ZN ( n77 ) , .VDD ( vdd ) , .INP ( n62 ) , .VSS ( gnd ) ) ;
NAND2X0 U42 (.VDD ( vdd ) , .IN1 ( n15 ) , .VSS ( gnd ) , .IN2 ( n70 ) 
    , .QN ( apsr[2] ) ) ;
NAND2X0 U41 (.VDD ( vdd ) , .IN1 ( operation[3] ) , .VSS ( gnd ) 
    , .IN2 ( psr[2] ) , .QN ( n15 ) ) ;
NAND3X0 U40 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n107 ) , .IN3 ( n14 ) 
    , .IN2 ( n13 ) , .IN1 ( n202 ) ) ;
NOR4X0 U39 (.VSS ( gnd ) , .IN2 ( N120 ) , .IN1 ( N121 ) , .IN3 ( N119 ) 
    , .VDD ( vdd ) , .IN4 ( N118 ) , .QN ( n14 ) ) ;
NOR4X0 U38 (.VSS ( gnd ) , .IN2 ( N116 ) , .IN1 ( N117 ) , .IN3 ( N115 ) 
    , .VDD ( vdd ) , .IN4 ( N114 ) , .QN ( n13 ) ) ;
AO21X1 U37 (.VDD ( vdd ) , .IN2 ( n200 ) , .IN1 ( n42 ) , .IN3 ( n12 ) 
    , .Q ( n72 ) , .VSS ( gnd ) ) ;
AND3X1 U36 (.IN2 ( n37 ) , .IN1 ( n78 ) , .IN3 ( n24 ) , .Q ( n12 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
AO222X1 U35 (.Q ( apsr[0] ) , .IN2 ( n23 ) , .IN1 ( n6 ) , .IN3 ( n11 ) 
    , .IN4 ( n23 ) , .IN6 ( psr[0] ) , .IN5 ( operation[3] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
NAND3X0 U34 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n11 ) , .IN3 ( n10 ) 
    , .IN2 ( n9 ) , .IN1 ( n8 ) ) ;
NAND3X0 U33 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n10 ) , .IN3 ( n120 ) 
    , .IN2 ( n199 ) , .IN1 ( n186 ) ) ;
NAND3X0 U32 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n9 ) , .IN3 ( n200 ) 
    , .IN2 ( n187 ) , .IN1 ( n124 ) ) ;
OA22X1 U31 (.IN2 ( n121 ) , .IN4 ( n37 ) , .VDD ( vdd ) , .IN1 ( n78 ) 
    , .IN3 ( n7 ) , .Q ( n8 ) , .VSS ( gnd ) ) ;
OA21X1 U30 (.IN2 ( n113 ) , .IN3 ( n121 ) , .VSS ( gnd ) , .IN1 ( n112 ) 
    , .VDD ( vdd ) , .Q ( n7 ) ) ;
NAND4X0 U29 (.IN1 ( n105 ) , .QN ( n6 ) , .IN2 ( n106 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n107 ) , .IN4 ( n5 ) ) ;
NAND3X0 U28 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n5 ) , .IN3 ( n102 ) 
    , .IN2 ( n101 ) , .IN1 ( n198 ) ) ;
AO222X1 U27 (.Q ( result[6] ) , .IN2 ( n4 ) , .IN1 ( n26 ) 
    , .IN3 ( operation[3] ) , .IN4 ( a_i[6] ) , .IN6 ( n23 ) , .IN5 ( n63 ) 
    , .VSS ( gnd ) , .VDD ( vdd ) ) ;
INVX0 U26 (.ZN ( n4 ) , .VDD ( vdd ) , .INP ( n25 ) , .VSS ( gnd ) ) ;
AO222X1 U24 (.Q ( result[0] ) , .IN2 ( n141 ) , .IN1 ( n4 ) , .IN3 ( n144 ) 
    , .IN4 ( n23 ) , .IN6 ( a_i[0] ) , .IN5 ( operation[3] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
OR2X1 U21 (.VDD ( vdd ) , .IN2 ( N100 ) , .IN1 ( n47 ) , .VSS ( gnd ) 
    , .Q ( n48 ) ) ;
INVX0 U16 (.ZN ( n78 ) , .VDD ( vdd ) , .INP ( b_i[6] ) , .VSS ( gnd ) ) ;
INVX0 U15 (.ZN ( n200 ) , .VDD ( vdd ) , .INP ( n199 ) , .VSS ( gnd ) ) ;
FADDX1 U11 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( n52 ) 
    , .B ( DP_OP_36J1_125_9744_n16 ) , .CI ( a_i[1] ) 
    , .CO ( DP_OP_36J1_125_9744_n15 ) , .S ( N98 ) ) ;
NOR2X0 U10 (.QN ( n155 ) , .IN1 ( a_i[2] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( b_i[2] ) ) ;
AND3X1 U9 (.IN2 ( n17 ) , .IN1 ( n110 ) , .IN3 ( operation[2] ) , .Q ( n142 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
INVX0 U3 (.ZN ( n57 ) , .VDD ( vdd ) , .INP ( N97 ) , .VSS ( gnd ) ) ;
FADDX1 add_x_1_U2 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( a_i[7] ) , .B ( b_i[7] ) 
    , .CI ( add_x_1_n2 ) , .CO ( N76 ) , .S ( N75 ) ) ;
FADDX1 add_x_1_U3 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( a_i[6] ) , .B ( b_i[6] ) 
    , .CI ( add_x_1_n3 ) , .CO ( add_x_1_n2 ) , .S ( N74 ) ) ;
FADDX1 add_x_1_U6 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[3] ) , .B ( a_i[3] ) 
    , .CI ( add_x_1_n6 ) , .CO ( add_x_1_n5 ) , .S ( N71 ) ) ;
FADDX1 add_x_1_U7 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( a_i[2] ) , .B ( b_i[2] ) 
    , .CI ( add_x_1_n7 ) , .CO ( add_x_1_n6 ) , .S ( N70 ) ) ;
FADDX1 add_x_1_U4 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( add_x_1_n4 ) 
    , .B ( b_i[5] ) , .CI ( a_i[5] ) , .CO ( add_x_1_n3 ) , .S ( N73 ) ) ;
FADDX1 add_x_1_U5 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( a_i[4] ) , .B ( b_i[4] ) 
    , .CI ( add_x_1_n5 ) , .CO ( add_x_1_n4 ) , .S ( N72 ) ) ;
FADDX1 add_x_1_U8 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( a_i[1] ) , .B ( b_i[1] ) 
    , .CI ( add_x_1_n8 ) , .CO ( add_x_1_n7 ) , .S ( N69 ) ) ;
FADDX1 DP_OP_35J1_124_9704_U2 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[7] ) 
    , .B ( a_i[7] ) , .CI ( DP_OP_35J1_124_9704_n2 ) , .CO ( N95 ) , .S ( N94 ) ) ;
FADDX1 DP_OP_35J1_124_9704_U3 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[6] ) 
    , .B ( a_i[6] ) , .CI ( DP_OP_35J1_124_9704_n3 ) 
    , .CO ( DP_OP_35J1_124_9704_n2 ) , .S ( N93 ) ) ;
FADDX1 DP_OP_35J1_124_9704_U4 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[5] ) 
    , .B ( a_i[5] ) , .CI ( DP_OP_35J1_124_9704_n4 ) 
    , .CO ( DP_OP_35J1_124_9704_n3 ) , .S ( N92 ) ) ;
FADDX1 DP_OP_35J1_124_9704_U5 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[4] ) 
    , .B ( a_i[4] ) , .CI ( DP_OP_35J1_124_9704_n5 ) 
    , .CO ( DP_OP_35J1_124_9704_n4 ) , .S ( N91 ) ) ;
FADDX1 DP_OP_35J1_124_9704_U6 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[3] ) 
    , .B ( a_i[3] ) , .CI ( DP_OP_35J1_124_9704_n6 ) 
    , .CO ( DP_OP_35J1_124_9704_n5 ) , .S ( N90 ) ) ;
FADDX1 DP_OP_35J1_124_9704_U8 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[1] ) 
    , .B ( a_i[1] ) , .CI ( DP_OP_35J1_124_9704_n8 ) 
    , .CO ( DP_OP_35J1_124_9704_n7 ) , .S ( N88 ) ) ;
FADDX1 DP_OP_35J1_124_9704_U9 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[0] ) 
    , .B ( a_i[0] ) , .CI ( psr[1] ) , .CO ( DP_OP_35J1_124_9704_n8 ) , .S ( N87 ) ) ;
FADDX1 DP_OP_36J1_125_9744_U19 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( a_i[6] ) 
    , .B ( n78 ) , .CI ( DP_OP_36J1_125_9744_n11 ) 
    , .CO ( DP_OP_36J1_125_9744_n10 ) , .S ( N103 ) ) ;
FADDX1 DP_OP_36J1_125_9744_U20 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( a_i[5] ) 
    , .B ( n79 ) , .CI ( DP_OP_36J1_125_9744_n12 ) 
    , .CO ( DP_OP_36J1_125_9744_n11 ) , .S ( N102 ) ) ;
FADDX1 DP_OP_36J1_125_9744_U23 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( n53 ) 
    , .B ( a_i[2] ) , .CI ( DP_OP_36J1_125_9744_n15 ) 
    , .CO ( DP_OP_36J1_125_9744_n14 ) , .S ( N99 ) ) ;
OR2X1 DP_OP_36J1_125_9744__cell_876 (.VDD ( vdd ) , .IN2 ( n45 ) , .IN1 ( N98 ) 
    , .VSS ( gnd ) , .Q ( n46 ) ) ;
XNOR2X1 DP_OP_36J1_125_9744__cell_875 (.VSS ( gnd ) , .IN1 ( N99 ) 
    , .IN2 ( n46 ) , .Q ( N116 ) , .VDD ( vdd ) ) ;
OR2X1 DP_OP_36J1_125_9744__cell_874 (.VDD ( vdd ) , .IN2 ( n46 ) , .IN1 ( N99 ) 
    , .VSS ( gnd ) , .Q ( n47 ) ) ;
XNOR3X1 DP_OP_36J1_125_9744__cell_865 (.Q ( N104 ) , .IN3 ( b_i[7] ) 
    , .VSS ( gnd ) , .IN2 ( a_i[7] ) , .IN1 ( DP_OP_36J1_125_9744_n10 ) 
    , .VDD ( vdd ) ) ;
XOR2X1 U147 (.VDD ( vdd ) , .VSS ( gnd ) , .IN2 ( b_i[0] ) , .Q ( N97 ) 
    , .IN1 ( a_i[0] ) ) ;
XNOR2X1 U146 (.VSS ( gnd ) , .IN1 ( N102 ) , .IN2 ( n49 ) , .Q ( N119 ) 
    , .VDD ( vdd ) ) ;
XNOR2X1 U145 (.VSS ( gnd ) , .IN1 ( N101 ) , .IN2 ( n48 ) , .Q ( N118 ) 
    , .VDD ( vdd ) ) ;
XNOR2X1 U144 (.VSS ( gnd ) , .IN1 ( N100 ) , .IN2 ( n47 ) , .Q ( N117 ) 
    , .VDD ( vdd ) ) ;
XNOR2X1 U143 (.VSS ( gnd ) , .IN1 ( N98 ) , .IN2 ( n45 ) , .Q ( N115 ) 
    , .VDD ( vdd ) ) ;
MUX21X1 U142 (.S ( psr[1] ) , .IN2 ( n57 ) , .IN1 ( N97 ) , .Q ( N114 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
NOR2X0 U140 (.QN ( n197 ) , .IN1 ( operation[2] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n97 ) ) ;
INVX0 U139 (.ZN ( n42 ) , .VDD ( vdd ) , .INP ( n128 ) , .VSS ( gnd ) ) ;
INVX0 U136 (.ZN ( n37 ) , .VDD ( vdd ) , .INP ( a_i[6] ) , .VSS ( gnd ) ) ;
NAND2X0 U135 (.VDD ( vdd ) , .IN1 ( n133 ) , .VSS ( gnd ) , .IN2 ( n142 ) 
    , .QN ( n74 ) ) ;
AOI22X1 U133 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( n129 ) , .IN2 ( n198 ) 
    , .IN3 ( n42 ) , .IN1 ( N104 ) , .QN ( n131 ) ) ;
NAND2X0 U131 (.VDD ( vdd ) , .IN1 ( n127 ) , .VSS ( gnd ) , .IN2 ( n77 ) 
    , .QN ( n65 ) ) ;
HADDX1 U125 (.VDD ( vdd ) , .VSS ( gnd ) , .B0 ( a_i[0] ) , .A0 ( b_i[0] ) 
    , .C1 ( add_x_1_n8 ) , .SO ( N68 ) ) ;
NAND2X1 U114 (.IN2 ( b_i[0] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( a_i[0] ) 
    , .QN ( n141 ) ) ;
MUX21X1 U113 (.S ( b_i[6] ) , .IN2 ( n37 ) , .IN1 ( a_i[6] ) , .Q ( n199 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
FADDX1 U112 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( b_i[2] ) , .B ( a_i[2] ) 
    , .CI ( DP_OP_35J1_124_9704_n7 ) , .CO ( DP_OP_35J1_124_9704_n6 ) , .S ( N89 ) ) ;
AOI22X1 U111 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N88 ) , .IN2 ( n24 ) 
    , .IN3 ( n197 ) , .IN1 ( n145 ) , .QN ( n151 ) ) ;
AOI22X1 U110 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N89 ) , .IN2 ( n24 ) 
    , .IN3 ( n197 ) , .IN1 ( n155 ) , .QN ( n161 ) ) ;
AOI22X1 U109 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N68 ) , .IN2 ( n135 ) 
    , .IN3 ( n196 ) , .IN1 ( n42 ) , .QN ( n139 ) ) ;
AOI22X1 U108 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N97 ) , .IN2 ( n77 ) 
    , .IN3 ( n198 ) , .IN1 ( n136 ) , .QN ( n138 ) ) ;
AOI22X1 U107 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( n157 ) , .IN2 ( n198 ) 
    , .IN3 ( n42 ) , .IN1 ( N99 ) , .QN ( n159 ) ) ;
AOI22X1 U106 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( n167 ) , .IN2 ( n198 ) 
    , .IN3 ( n42 ) , .IN1 ( N100 ) , .QN ( n169 ) ) ;
AOI22X1 U105 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( n146 ) , .IN2 ( n196 ) 
    , .IN3 ( n42 ) , .IN1 ( N69 ) , .QN ( n150 ) ) ;
AOI22X1 U104 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( n177 ) , .IN2 ( n198 ) 
    , .IN3 ( n42 ) , .IN1 ( N101 ) , .QN ( n179 ) ) ;
AOI22X1 U103 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N73 ) , .IN2 ( n77 ) 
    , .IN3 ( n196 ) , .IN1 ( n186 ) , .QN ( n190 ) ) ;
AOI22X1 U102 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N74 ) , .IN2 ( N93 ) 
    , .IN3 ( n196 ) , .IN1 ( n197 ) , .QN ( n61 ) ) ;
AOI22X1 U101 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N94 ) , .IN2 ( n24 ) 
    , .IN3 ( n197 ) , .IN1 ( n126 ) , .QN ( n132 ) ) ;
AO22X1 U100 (.IN1 ( n199 ) , .VSS ( gnd ) , .IN3 ( n198 ) , .VDD ( vdd ) 
    , .IN2 ( n77 ) , .Q ( n203 ) , .IN4 ( N103 ) ) ;
AND2X1 U99 (.IN1 ( N75 ) , .IN2 ( n196 ) , .Q ( n66 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
NAND3X0 U98 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n105 ) , .IN3 ( n103 ) 
    , .IN2 ( n104 ) , .IN1 ( n196 ) ) ;
NAND2X0 U97 (.VDD ( vdd ) , .IN1 ( n202 ) , .VSS ( gnd ) , .IN2 ( N119 ) 
    , .QN ( n188 ) ) ;
XOR2X1 U96 (.VDD ( vdd ) , .VSS ( gnd ) , .IN2 ( n51 ) , .Q ( N121 ) 
    , .IN1 ( N104 ) ) ;
AND2X1 U90 (.IN1 ( a_i[5] ) , .IN2 ( b_i[5] ) , .Q ( n192 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
NOR2X0 U89 (.QN ( n166 ) , .IN1 ( n165 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n172 ) ) ;
AOI22X1 U88 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N90 ) , .IN2 ( n24 ) 
    , .IN3 ( n197 ) , .IN1 ( n165 ) , .QN ( n171 ) ) ;
AOI22X1 U87 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N71 ) , .IN2 ( n77 ) 
    , .IN3 ( n196 ) , .IN1 ( n166 ) , .QN ( n170 ) ) ;
NOR4X0 U86 (.VSS ( gnd ) , .IN2 ( n136 ) , .IN1 ( n127 ) , .IN3 ( n62 ) 
    , .VDD ( vdd ) , .IN4 ( n123 ) , .QN ( n124 ) ) ;
AOI22X1 U84 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N70 ) , .IN2 ( n77 ) 
    , .IN3 ( n196 ) , .IN1 ( n156 ) , .QN ( n160 ) ) ;
AOI22X1 U83 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( n187 ) , .IN2 ( n198 ) 
    , .IN3 ( n42 ) , .IN1 ( N102 ) , .QN ( n189 ) ) ;
NOR4X0 U82 (.VSS ( gnd ) , .IN2 ( N103 ) , .IN1 ( N104 ) , .IN3 ( N102 ) 
    , .VDD ( vdd ) , .IN4 ( N101 ) , .QN ( n102 ) ) ;
XNOR2X1 U81 (.VSS ( gnd ) , .IN1 ( N103 ) , .IN2 ( n50 ) , .Q ( N120 ) 
    , .VDD ( vdd ) ) ;
INVX0 U80 (.ZN ( n187 ) , .VDD ( vdd ) , .INP ( n186 ) , .VSS ( gnd ) ) ;
NAND3X0 U79 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n128 ) , .IN3 ( operation[0] ) 
    , .IN2 ( operation[1] ) , .IN1 ( operation[2] ) ) ;
NAND2X0 U78 (.VDD ( vdd ) , .IN1 ( operation[0] ) , .VSS ( gnd ) , .IN2 ( n110 ) 
    , .QN ( n100 ) ) ;
INVX0 U76 (.ZN ( n80 ) , .VDD ( vdd ) , .INP ( b_i[3] ) , .VSS ( gnd ) ) ;
INVX0 U75 (.ZN ( n79 ) , .VDD ( vdd ) , .INP ( b_i[5] ) , .VSS ( gnd ) ) ;
INVX0 U74 (.ZN ( n54 ) , .VDD ( vdd ) , .INP ( b_i[4] ) , .VSS ( gnd ) ) ;
AND2X1 U73 (.IN1 ( a_i[4] ) , .IN2 ( b_i[4] ) , .Q ( n182 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
NOR2X0 U72 (.QN ( n165 ) , .IN1 ( a_i[3] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( b_i[3] ) ) ;
AO22X1 U70 (.IN1 ( n197 ) , .VSS ( gnd ) , .IN3 ( n196 ) , .VDD ( vdd ) 
    , .IN2 ( N95 ) , .Q ( n125 ) , .IN4 ( N76 ) ) ;
NOR2X0 U68 (.QN ( n126 ) , .IN1 ( a_i[7] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( b_i[7] ) ) ;
NAND2X1 U67 (.IN2 ( b_i[3] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( a_i[3] ) 
    , .QN ( n116 ) ) ;
NOR2X0 U66 (.QN ( n185 ) , .IN1 ( a_i[5] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( b_i[5] ) ) ;
NAND2X1 U65 (.IN2 ( b_i[7] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( a_i[7] ) 
    , .QN ( n133 ) ) ;
NOR2X0 U64 (.QN ( n175 ) , .IN1 ( a_i[4] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( b_i[4] ) ) ;
INVX0 U63 (.ZN ( n53 ) , .VDD ( vdd ) , .INP ( b_i[2] ) , .VSS ( gnd ) ) ;
NAND2X1 U62 (.IN2 ( b_i[2] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( a_i[2] ) 
    , .QN ( n117 ) ) ;
INVX0 U61 (.ZN ( n52 ) , .VDD ( vdd ) , .INP ( b_i[1] ) , .VSS ( gnd ) ) ;
NAND2X0 U60 (.VDD ( vdd ) , .IN1 ( operation[1] ) , .VSS ( gnd ) 
    , .IN2 ( operation[0] ) , .QN ( n96 ) ) ;
NAND2X0 U59 (.VDD ( vdd ) , .IN1 ( n202 ) , .VSS ( gnd ) , .IN2 ( N118 ) 
    , .QN ( n178 ) ) ;
AO221X1 U237 (.IN5 ( n193 ) , .Q ( result[5] ) , .VSS ( gnd ) , .IN2 ( a_i[5] ) 
    , .IN1 ( operation[3] ) , .IN3 ( n23 ) , .VDD ( vdd ) , .IN4 ( n194 ) ) ;
NAND4X0 U236 (.IN1 ( n188 ) , .QN ( n194 ) , .IN2 ( n190 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n189 ) , .IN4 ( n191 ) ) ;
AO221X1 U235 (.IN5 ( n183 ) , .Q ( result[4] ) , .VSS ( gnd ) , .IN2 ( a_i[4] ) 
    , .IN1 ( operation[3] ) , .IN3 ( n23 ) , .VDD ( vdd ) , .IN4 ( n184 ) ) ;
NAND4X0 U234 (.IN1 ( n178 ) , .QN ( n184 ) , .IN2 ( n180 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n179 ) , .IN4 ( n181 ) ) ;
AO221X1 U233 (.IN5 ( n173 ) , .Q ( result[3] ) , .VSS ( gnd ) , .IN2 ( a_i[3] ) 
    , .IN1 ( operation[3] ) , .IN3 ( n174 ) , .VDD ( vdd ) , .IN4 ( n23 ) ) ;
NAND4X0 U232 (.IN1 ( n171 ) , .QN ( n174 ) , .IN2 ( n170 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n169 ) , .IN4 ( n168 ) ) ;
AO221X1 U231 (.IN5 ( n163 ) , .Q ( result[2] ) , .VSS ( gnd ) , .IN2 ( a_i[2] ) 
    , .IN1 ( operation[3] ) , .IN3 ( n164 ) , .VDD ( vdd ) , .IN4 ( n23 ) ) ;
NAND4X0 U230 (.IN1 ( n161 ) , .QN ( n164 ) , .IN2 ( n160 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n159 ) , .IN4 ( n158 ) ) ;
AO221X1 U229 (.IN5 ( n153 ) , .Q ( result[1] ) , .VSS ( gnd ) , .IN2 ( a_i[1] ) 
    , .IN1 ( operation[3] ) , .IN3 ( n154 ) , .VDD ( vdd ) , .IN4 ( n23 ) ) ;
NAND4X0 U228 (.IN1 ( n151 ) , .QN ( n154 ) , .IN2 ( n150 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n149 ) , .IN4 ( n148 ) ) ;
NAND4X0 U226 (.IN1 ( n140 ) , .QN ( n144 ) , .IN2 ( n139 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n138 ) , .IN4 ( n137 ) ) ;
AOI22X1 U225 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N87 ) , .IN2 ( n134 ) 
    , .IN3 ( n197 ) , .IN1 ( n24 ) , .QN ( n140 ) ) ;
MUX21X1 U224 (.S ( operation[3] ) , .IN2 ( psr[1] ) , .IN1 ( n125 ) 
    , .Q ( apsr[1] ) , .VDD ( vdd ) , .VSS ( gnd ) ) ;
NAND4X0 U223 (.IN1 ( n177 ) , .QN ( n123 ) , .IN2 ( n167 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n157 ) , .IN4 ( n146 ) ) ;
INVX0 U222 (.ZN ( n177 ) , .VDD ( vdd ) , .INP ( n176 ) , .VSS ( gnd ) ) ;
INVX0 U221 (.ZN ( n136 ) , .VDD ( vdd ) , .INP ( n135 ) , .VSS ( gnd ) ) ;
NAND4X0 U220 (.IN1 ( n176 ) , .QN ( n119 ) , .IN2 ( n166 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n156 ) , .IN4 ( n147 ) ) ;
NOR4X0 U219 (.VSS ( gnd ) , .IN2 ( n117 ) , .IN1 ( n116 ) , .IN3 ( n118 ) 
    , .VDD ( vdd ) , .IN4 ( n141 ) , .QN ( n111 ) ) ;
NAND4X0 U218 (.IN1 ( a_i[5] ) , .QN ( n113 ) , .IN2 ( b_i[5] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( a_i[4] ) , .IN4 ( b_i[4] ) ) ;
NAND4X0 U217 (.IN1 ( n24 ) , .QN ( n121 ) , .IN2 ( n109 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n108 ) , .IN4 ( n115 ) ) ;
INVX0 U216 (.ZN ( n115 ) , .VDD ( vdd ) , .INP ( n134 ) , .VSS ( gnd ) ) ;
NOR2X0 U215 (.QN ( n134 ) , .IN1 ( a_i[0] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( b_i[0] ) ) ;
NOR4X0 U214 (.VSS ( gnd ) , .IN2 ( n165 ) , .IN1 ( n175 ) , .IN3 ( n155 ) 
    , .VDD ( vdd ) , .IN4 ( n145 ) , .QN ( n108 ) ) ;
NOR2X0 U213 (.QN ( n109 ) , .IN1 ( n126 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n185 ) ) ;
NOR4X0 U212 (.VSS ( gnd ) , .IN2 ( N70 ) , .IN1 ( N71 ) , .IN3 ( N69 ) 
    , .VDD ( vdd ) , .IN4 ( N68 ) , .QN ( n103 ) ) ;
NOR4X0 U211 (.VSS ( gnd ) , .IN2 ( N74 ) , .IN1 ( N75 ) , .IN3 ( N73 ) 
    , .VDD ( vdd ) , .IN4 ( N72 ) , .QN ( n104 ) ) ;
NOR4X0 U210 (.VSS ( gnd ) , .IN2 ( N99 ) , .IN1 ( N100 ) , .IN3 ( N98 ) 
    , .VDD ( vdd ) , .IN4 ( N97 ) , .QN ( n101 ) ) ;
NAND3X0 U209 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n106 ) , .IN3 ( n98 ) 
    , .IN2 ( n99 ) , .IN1 ( n197 ) ) ;
NOR4X0 U208 (.VSS ( gnd ) , .IN2 ( N89 ) , .IN1 ( N90 ) , .IN3 ( N88 ) 
    , .VDD ( vdd ) , .IN4 ( N87 ) , .QN ( n98 ) ) ;
NOR4X0 U207 (.VSS ( gnd ) , .IN2 ( N93 ) , .IN1 ( N94 ) , .IN3 ( N92 ) 
    , .VDD ( vdd ) , .IN4 ( N91 ) , .QN ( n99 ) ) ;
NAND4X0 U206 (.IN1 ( n132 ) , .QN ( n68 ) , .IN2 ( n67 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( n130 ) , .IN4 ( n131 ) ) ;
NAND3X0 U205 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n63 ) , .IN3 ( n61 ) 
    , .IN2 ( n73 ) , .IN1 ( n71 ) ) ;
NAND4X0 U203 (.IN1 ( n114 ) , .QN ( n112 ) , .IN2 ( n142 ) , .VSS ( gnd ) 
    , .VDD ( vdd ) , .IN3 ( b_i[6] ) , .IN4 ( n111 ) ) ;
AOI22X1 U202 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N92 ) , .IN2 ( n24 ) 
    , .IN3 ( n197 ) , .IN1 ( n185 ) , .QN ( n191 ) ) ;
AOI22X1 U201 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N91 ) , .IN2 ( n24 ) 
    , .IN3 ( n197 ) , .IN1 ( n175 ) , .QN ( n181 ) ) ;
AOI22X1 U200 (.VSS ( gnd ) , .VDD ( vdd ) , .IN4 ( N98 ) , .IN2 ( n77 ) 
    , .IN3 ( n198 ) , .IN1 ( n147 ) , .QN ( n149 ) ) ;
NAND2X1 U199 (.IN2 ( n74 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n65 ) 
    , .QN ( n64 ) ) ;
NAND2X1 U198 (.IN2 ( a_i[7] ) , .VSS ( gnd ) , .VDD ( vdd ) 
    , .IN1 ( operation[3] ) , .QN ( n69 ) ) ;
NAND2X1 U197 (.IN2 ( n202 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( N120 ) 
    , .QN ( n73 ) ) ;
NAND2X1 U195 (.IN2 ( a_i[1] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( b_i[1] ) 
    , .QN ( n118 ) ) ;
NAND2X1 U194 (.IN2 ( n141 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n115 ) 
    , .QN ( n135 ) ) ;
NAND2X1 U193 (.IN2 ( N116 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n202 ) 
    , .QN ( n158 ) ) ;
NAND2X1 U192 (.IN2 ( N114 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n202 ) 
    , .QN ( n137 ) ) ;
NAND2X1 U191 (.IN2 ( N117 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n202 ) 
    , .QN ( n168 ) ) ;
NAND2X1 U190 (.IN2 ( N115 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n202 ) 
    , .QN ( n148 ) ) ;
NOR2X0 U189 (.QN ( n193 ) , .IN1 ( n192 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n25 ) ) ;
NOR2X0 U188 (.QN ( n163 ) , .IN1 ( n162 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n25 ) ) ;
NOR2X0 U187 (.QN ( n173 ) , .IN1 ( n172 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n25 ) ) ;
NOR2X0 U186 (.QN ( n153 ) , .IN1 ( n152 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n25 ) ) ;
INVX0 U185 (.ZN ( n110 ) , .VDD ( vdd ) , .INP ( operation[1] ) , .VSS ( gnd ) ) ;
NOR2X0 U180 (.QN ( n202 ) , .IN1 ( operation[2] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n96 ) ) ;
INVX0 U179 (.ZN ( n114 ) , .VDD ( vdd ) , .INP ( n133 ) , .VSS ( gnd ) ) ;
NOR2X0 U178 (.QN ( n127 ) , .IN1 ( n126 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n114 ) ) ;
NOR2X0 U177 (.QN ( n67 ) , .IN1 ( n66 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n64 ) ) ;
NOR2X0 U176 (.QN ( n198 ) , .IN1 ( operation[2] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n100 ) ) ;
INVX0 U174 (.ZN ( n129 ) , .VDD ( vdd ) , .INP ( n127 ) , .VSS ( gnd ) ) ;
NOR2X0 U172 (.QN ( n71 ) , .IN1 ( n203 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n72 ) ) ;
NOR2X0 U171 (.QN ( n145 ) , .IN1 ( b_i[1] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( a_i[1] ) ) ;
NOR2X0 U170 (.QN ( n186 ) , .IN1 ( n185 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n192 ) ) ;
NOR2X0 U169 (.QN ( n176 ) , .IN1 ( n175 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n182 ) ) ;
INVX0 U168 (.ZN ( n172 ) , .VDD ( vdd ) , .INP ( n116 ) , .VSS ( gnd ) ) ;
INVX0 U167 (.ZN ( n162 ) , .VDD ( vdd ) , .INP ( n117 ) , .VSS ( gnd ) ) ;
NOR2X0 U166 (.QN ( n156 ) , .IN1 ( n155 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n162 ) ) ;
INVX0 U165 (.ZN ( n152 ) , .VDD ( vdd ) , .INP ( n118 ) , .VSS ( gnd ) ) ;
NOR2X0 U164 (.QN ( n147 ) , .IN1 ( n145 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n152 ) ) ;
NOR4X0 U163 (.VSS ( gnd ) , .IN2 ( n128 ) , .IN1 ( n129 ) , .IN3 ( n135 ) 
    , .VDD ( vdd ) , .IN4 ( n119 ) , .QN ( n120 ) ) ;
INVX0 U162 (.ZN ( n167 ) , .VDD ( vdd ) , .INP ( n166 ) , .VSS ( gnd ) ) ;
INVX0 U161 (.ZN ( n157 ) , .VDD ( vdd ) , .INP ( n156 ) , .VSS ( gnd ) ) ;
INVX0 U160 (.ZN ( n146 ) , .VDD ( vdd ) , .INP ( n147 ) , .VSS ( gnd ) ) ;
NOR2X0 U158 (.QN ( n183 ) , .IN1 ( n182 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n25 ) ) ;
NAND2X0 U157 (.VDD ( vdd ) , .IN1 ( n69 ) , .VSS ( gnd ) , .IN2 ( n70 ) 
    , .QN ( result[7] ) ) ;
NAND2X1 U156 (.IN2 ( b_i[0] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n56 ) 
    , .QN ( DP_OP_36J1_125_9744_n16 ) ) ;
NOR2X0 U155 (.QN ( n51 ) , .IN1 ( N103 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n50 ) ) ;
NOR2X0 U154 (.QN ( n60 ) , .IN1 ( n48 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( N101 ) ) ;
NAND2X1 U153 (.IN2 ( n57 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( psr[1] ) 
    , .QN ( n45 ) ) ;
INVX0 U152 (.ZN ( n49 ) , .VDD ( vdd ) , .INP ( n60 ) , .VSS ( gnd ) ) ;
FADDX1 U151 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( n54 ) , .B ( a_i[4] ) 
    , .CI ( DP_OP_36J1_125_9744_n13 ) , .CO ( DP_OP_36J1_125_9744_n12 ) 
    , .S ( N101 ) ) ;
INVX0 U150 (.ZN ( n59 ) , .VDD ( vdd ) , .INP ( N102 ) , .VSS ( gnd ) ) ;
FADDX1 U149 (.VDD ( vdd ) , .VSS ( gnd ) , .A ( n80 ) , .B ( a_i[3] ) 
    , .CI ( DP_OP_36J1_125_9744_n14 ) , .CO ( DP_OP_36J1_125_9744_n13 ) 
    , .S ( N100 ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_pc (CLK , EN , ENCLK , vdd , gnd );
input  CLK ;
input  EN ;
output ENCLK ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


INVX0 U2 (.ZN ( n1 ) , .VDD ( vdd ) , .INP ( CLK ) , .VSS ( gnd ) ) ;
LATCHX1 latch (.VDD ( vdd ) , .VSS ( gnd ) , .D ( EN ) , .CLK ( n1 ) 
    , .Q ( net344 ) ) ;
AND2X2 main_gate (.IN1 ( net344 ) , .IN2 ( CLK ) , .Q ( ENCLK ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
endmodule




module pc (rst , clk , count_BAR , load , addr_in , addr_out , vdd , 
    gnd );
input  rst ;
input  clk ;
input  count_BAR ;
input  load ;
input  [7:0] addr_in ;
output [7:0] addr_out ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;



SNPS_CLOCK_GATE_HIGH_pc clk_gate_addr_out_reg (.CLK ( clk ) , .EN ( N3 ) , 
    .ENCLK ( net350 ) , .vdd ( vdd ) , .gnd ( gnd ) ) ;

INVX0 U4 (.ZN ( n2 ) , .VDD ( vdd ) , .INP ( load ) , .VSS ( gnd ) ) ;
AO22X1 U22 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[4] ) , .Q ( N17 ) , .IN4 ( n28 ) ) ;
AO22X1 U21 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[2] ) , .Q ( N15 ) , .IN4 ( n24 ) ) ;
AO22X1 U20 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[0] ) , .Q ( N13 ) , .IN4 ( n17 ) ) ;
AO22X1 U19 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[3] ) , .Q ( N16 ) , .IN4 ( n25 ) ) ;
AO22X1 U18 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[1] ) , .Q ( N14 ) , .IN4 ( n21 ) ) ;
NOR2X0 U14 (.QN ( n37 ) , .IN1 ( count_BAR ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( load ) ) ;
NAND2X0 U9 (.VDD ( vdd ) , .IN1 ( addr_out[1] ) , .VSS ( gnd ) 
    , .IN2 ( addr_out[0] ) , .QN ( n22 ) ) ;
NAND2X0 U6 (.VDD ( vdd ) , .IN1 ( count_BAR ) , .VSS ( gnd ) , .IN2 ( n2 ) 
    , .QN ( N3 ) ) ;
NAND3X0 U3 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( n26 ) , .IN3 ( addr_out[2] ) 
    , .IN2 ( addr_out[0] ) , .IN1 ( addr_out[1] ) ) ;
DFFARX1 addr_out_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .QN ( n17 ) , .Q ( addr_out[0] ) , .D ( N13 ) ) ;
DFFARX1 addr_out_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .Q ( addr_out[1] ) , .D ( N14 ) ) ;
DFFARX1 addr_out_reg_2_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .Q ( addr_out[2] ) , .D ( N15 ) ) ;
DFFARX1 addr_out_reg_3_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .QN ( n7 ) , .Q ( addr_out[3] ) , .D ( N16 ) ) ;
DFFARX1 addr_out_reg_4_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .Q ( addr_out[4] ) , .D ( N17 ) ) ;
DFFARX1 addr_out_reg_5_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .QN ( n13 ) , .Q ( addr_out[5] ) , .D ( N18 ) ) ;
DFFARX1 addr_out_reg_6_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .Q ( addr_out[6] ) , .D ( N19 ) ) ;
DFFARX1 addr_out_reg_7_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net350 ) 
    , .RSTB ( rst ) , .QN ( n35 ) , .Q ( addr_out[7] ) , .D ( N20 ) ) ;
MUX21X1 U40 (.S ( n34 ) , .IN2 ( addr_out[7] ) , .IN1 ( n35 ) , .Q ( n36 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
OA21X1 U39 (.IN2 ( addr_out[6] ) , .IN3 ( n34 ) , .VSS ( gnd ) , .IN1 ( n32 ) 
    , .VDD ( vdd ) , .Q ( n33 ) ) ;
NOR2X0 U38 (.QN ( n32 ) , .IN1 ( n31 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n13 ) ) ;
OA21X1 U36 (.IN2 ( addr_out[4] ) , .IN3 ( n31 ) , .VSS ( gnd ) , .IN1 ( n27 ) 
    , .VDD ( vdd ) , .Q ( n28 ) ) ;
NOR2X0 U35 (.QN ( n27 ) , .IN1 ( n26 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n7 ) ) ;
OA21X1 U34 (.IN2 ( addr_out[2] ) , .IN3 ( n26 ) , .VSS ( gnd ) , .IN1 ( n23 ) 
    , .VDD ( vdd ) , .Q ( n24 ) ) ;
INVX0 U33 (.ZN ( n23 ) , .VDD ( vdd ) , .INP ( n22 ) , .VSS ( gnd ) ) ;
OA21X1 U32 (.IN2 ( addr_out[0] ) , .IN3 ( n22 ) , .VSS ( gnd ) 
    , .IN1 ( addr_out[1] ) , .VDD ( vdd ) , .Q ( n21 ) ) ;
MUX21X1 U29 (.S ( n31 ) , .IN2 ( addr_out[5] ) , .IN1 ( n13 ) , .Q ( n29 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
MUX21X1 U28 (.S ( n26 ) , .IN2 ( addr_out[3] ) , .IN1 ( n7 ) , .Q ( n25 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
AO22X1 U27 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[7] ) , .Q ( N20 ) , .IN4 ( n36 ) ) ;
AO22X1 U26 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[6] ) , .Q ( N19 ) , .IN4 ( n33 ) ) ;
NAND2X1 U25 (.IN2 ( addr_out[4] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n27 ) 
    , .QN ( n31 ) ) ;
NAND2X1 U24 (.IN2 ( addr_out[6] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n32 ) 
    , .QN ( n34 ) ) ;
AO22X1 U23 (.IN1 ( load ) , .VSS ( gnd ) , .IN3 ( n37 ) , .VDD ( vdd ) 
    , .IN2 ( addr_in[5] ) , .Q ( N18 ) , .IN4 ( n29 ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_regs_1 (CLK , EN , ENCLK , vdd , gnd );
input  CLK ;
input  EN ;
output ENCLK ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


INVX0 U2 (.ZN ( n2 ) , .VDD ( vdd ) , .INP ( CLK ) , .VSS ( gnd ) ) ;
LATCHX1 latch (.VDD ( vdd ) , .VSS ( gnd ) , .D ( EN ) , .CLK ( n2 ) 
    , .Q ( net359 ) ) ;
AND2X2 main_gate (.IN1 ( net359 ) , .IN2 ( CLK ) , .Q ( ENCLK ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_regs_3 (CLK , EN , ENCLK , vdd , gnd );
input  CLK ;
input  EN ;
output ENCLK ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


INVX0 U2 (.ZN ( n2 ) , .VDD ( vdd ) , .INP ( CLK ) , .VSS ( gnd ) ) ;
LATCHX1 latch (.VDD ( vdd ) , .VSS ( gnd ) , .D ( EN ) , .CLK ( n2 ) 
    , .Q ( net359 ) ) ;
AND2X2 main_gate (.IN1 ( net359 ) , .IN2 ( CLK ) , .Q ( ENCLK ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_regs_4 (CLK , EN , ENCLK , vdd , gnd );
input  CLK ;
input  EN ;
output ENCLK ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


INVX0 U2 (.ZN ( n2 ) , .VDD ( vdd ) , .INP ( CLK ) , .VSS ( gnd ) ) ;
LATCHX1 latch (.VDD ( vdd ) , .VSS ( gnd ) , .D ( EN ) , .CLK ( n2 ) 
    , .Q ( net359 ) ) ;
AND2X2 main_gate (.IN1 ( net359 ) , .IN2 ( CLK ) , .Q ( ENCLK ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_regs_0 (CLK , EN , ENCLK , vdd , gnd );
input  CLK ;
input  EN ;
output ENCLK ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


INVX0 U2 (.ZN ( n1 ) , .VDD ( vdd ) , .INP ( CLK ) , .VSS ( gnd ) ) ;
LATCHX1 latch (.VDD ( vdd ) , .VSS ( gnd ) , .D ( EN ) , .CLK ( n1 ) 
    , .Q ( net359 ) ) ;
AND2X2 main_gate (.IN1 ( net359 ) , .IN2 ( CLK ) , .Q ( ENCLK ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
endmodule




module regs (rst , clk , dmem_update , dmem_data , imem_update , 
    imem_data , opcode_update , opcode , psr_update , apsr , psr , 
    res_update , res_sel , alu , opa_sel , opb_sel , opa , opb , pc , 
    vdd , gnd , IN0 );
input  rst ;
input  clk ;
input  dmem_update ;
input  [7:0] dmem_data ;
input  imem_update ;
input  [7:0] imem_data ;
input  opcode_update ;
output [7:0] opcode ;
input  psr_update ;
input  [2:0] apsr ;
output [2:0] psr ;
input  res_update ;
input  [1:0] res_sel ;
input  [7:0] alu ;
input  [1:0] opa_sel ;
input  [1:0] opb_sel ;
output [7:0] opa ;
output [7:0] opb ;
input  [7:0] pc ;
input  vdd ;
input  gnd ;
input  IN0 ;

supply1 vdd ;
supply0 gnd ;

wire [7:0] imem ;
wire [7:0] acc ;


SNPS_CLOCK_GATE_HIGH_regs_1 clk_gate_acc_reg (.CLK ( clk ) , 
    .EN ( res_update ) , .ENCLK ( net385 ) , .vdd ( vdd ) , .gnd ( gnd ) ) ;


SNPS_CLOCK_GATE_HIGH_regs_3 clk_gate_imem_reg (.CLK ( clk ) , 
    .EN ( imem_update ) , .ENCLK ( net375 ) , .vdd ( vdd ) , .gnd ( gnd ) ) ;


SNPS_CLOCK_GATE_HIGH_regs_4 clk_gate_psr_reg (.CLK ( clk ) , 
    .EN ( psr_update ) , .ENCLK ( net370 ) , .vdd ( vdd ) , .gnd ( gnd ) ) ;


SNPS_CLOCK_GATE_HIGH_regs_0 clk_gate_opcode_reg (.CLK ( clk ) , 
    .EN ( opcode_update ) , .ENCLK ( net365 ) , .vdd ( vdd ) , .gnd ( gnd ) ) ;

NOR2X0 U22 (.IN1 ( n23 ) , .VDD ( vdd ) , .VSS ( gnd ) , .IN2 ( n21 ) 
    , .QN ( n22 ) ) ;
NAND2X0 U13 (.VDD ( vdd ) , .IN1 ( n38 ) , .VSS ( gnd ) , .IN2 ( pc[4] ) 
    , .QN ( n30 ) ) ;
NAND2X1 U12 (.IN2 ( n57 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( pc[1] ) 
    , .QN ( n43 ) ) ;
NAND2X1 U11 (.IN2 ( pc[2] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n38 ) 
    , .QN ( n24 ) ) ;
NOR2X0 U10 (.QN ( n37 ) , .IN1 ( opa_sel[1] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n2 ) ) ;
INVX0 U9 (.ZN ( n2 ) , .VDD ( vdd ) , .INP ( opa_sel[0] ) , .VSS ( gnd ) ) ;
AO222X1 U8 (.Q ( opb[7] ) , .IN2 ( imem[7] ) , .IN1 ( n56 ) , .IN3 ( n57 ) 
    , .IN4 ( pc[7] ) , .IN6 ( acc[7] ) , .IN5 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) ) ;
AO222X1 U7 (.Q ( opa[5] ) , .IN2 ( n37 ) , .IN1 ( imem[5] ) , .IN3 ( pc[5] ) 
    , .IN4 ( n38 ) , .IN6 ( n36 ) , .IN5 ( acc[5] ) , .VSS ( gnd ) , .VDD ( vdd ) ) ;
AO222X1 U6 (.Q ( opb[6] ) , .IN2 ( imem[6] ) , .IN1 ( n56 ) , .IN3 ( n57 ) 
    , .IN4 ( pc[6] ) , .IN6 ( acc[6] ) , .IN5 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) ) ;
AO222X1 U5 (.Q ( opa[1] ) , .IN2 ( n37 ) , .IN1 ( imem[1] ) , .IN3 ( pc[1] ) 
    , .IN4 ( n38 ) , .IN6 ( n36 ) , .IN5 ( acc[1] ) , .VSS ( gnd ) , .VDD ( vdd ) ) ;
AO222X1 U4 (.Q ( opb[5] ) , .IN2 ( imem[5] ) , .IN1 ( n56 ) , .IN3 ( n57 ) 
    , .IN4 ( pc[5] ) , .IN6 ( acc[5] ) , .IN5 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) ) ;
AO222X1 U3 (.Q ( opa[7] ) , .IN2 ( n37 ) , .IN1 ( imem[7] ) , .IN3 ( pc[7] ) 
    , .IN4 ( n38 ) , .IN6 ( n36 ) , .IN5 ( acc[7] ) , .VSS ( gnd ) , .VDD ( vdd ) ) ;
OR2X1 U2 (.VDD ( vdd ) , .IN2 ( n5 ) , .IN1 ( n6 ) , .VSS ( gnd ) , .Q ( n46 ) ) ;
DFFARX1 acc_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[0] ) , .D ( N19 ) ) ;
DFFARX1 acc_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[1] ) , .D ( N20 ) ) ;
DFFARX1 acc_reg_2_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[2] ) , .D ( N21 ) ) ;
DFFARX1 acc_reg_3_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[3] ) , .D ( N22 ) ) ;
DFFARX1 acc_reg_4_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[4] ) , .D ( N23 ) ) ;
DFFARX1 acc_reg_5_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[5] ) , .D ( N24 ) ) ;
DFFARX1 acc_reg_6_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[6] ) , .D ( N25 ) ) ;
DFFARX1 acc_reg_7_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net385 ) 
    , .RSTB ( IN0 ) , .Q ( acc[7] ) , .D ( N26 ) ) ;
DFFARX1 imem_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[0] ) , .D ( imem_data[0] ) ) ;
DFFARX1 imem_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[1] ) , .D ( imem_data[1] ) ) ;
DFFARX1 imem_reg_2_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[2] ) , .D ( imem_data[2] ) ) ;
DFFARX1 imem_reg_3_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[3] ) , .D ( imem_data[3] ) ) ;
DFFARX1 imem_reg_4_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[4] ) , .D ( imem_data[4] ) ) ;
DFFARX1 imem_reg_5_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[5] ) , .D ( imem_data[5] ) ) ;
DFFARX1 imem_reg_6_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[6] ) , .D ( imem_data[6] ) ) ;
DFFARX1 imem_reg_7_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net375 ) 
    , .RSTB ( IN0 ) , .Q ( imem[7] ) , .D ( imem_data[7] ) ) ;
DFFARX1 psr_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net370 ) 
    , .RSTB ( rst ) , .Q ( psr[0] ) , .D ( apsr[0] ) ) ;
DFFARX1 psr_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net370 ) 
    , .RSTB ( IN0 ) , .Q ( psr[1] ) , .D ( apsr[1] ) ) ;
DFFARX1 psr_reg_2_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net370 ) 
    , .RSTB ( rst ) , .Q ( psr[2] ) , .D ( apsr[2] ) ) ;
DFFARX1 opcode_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[0] ) , .D ( imem_data[0] ) ) ;
DFFARX1 opcode_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[1] ) , .D ( imem_data[1] ) ) ;
DFFARX1 opcode_reg_2_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[2] ) , .D ( imem_data[2] ) ) ;
DFFARX1 opcode_reg_3_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[3] ) , .D ( imem_data[3] ) ) ;
DFFARX1 opcode_reg_4_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[4] ) , .D ( imem_data[4] ) ) ;
DFFARX1 opcode_reg_5_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[5] ) , .D ( imem_data[5] ) ) ;
DFFARX1 opcode_reg_6_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[6] ) , .D ( imem_data[6] ) ) ;
DFFARX1 opcode_reg_7_ (.VDD ( vdd ) , .VSS ( gnd ) , .CLK ( net365 ) 
    , .RSTB ( IN0 ) , .Q ( opcode[7] ) , .D ( imem_data[7] ) ) ;
INVX0 U78 (.ZN ( n39 ) , .VDD ( vdd ) , .INP ( opb_sel[0] ) , .VSS ( gnd ) ) ;
AND2X1 U77 (.IN1 ( opa_sel[1] ) , .IN2 ( opa_sel[0] ) , .Q ( n38 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
NOR2X0 U76 (.QN ( n36 ) , .IN1 ( opa_sel[1] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( opa_sel[0] ) ) ;
AO222X1 U75 (.Q ( N25 ) , .IN2 ( imem_data[6] ) , .IN1 ( n23 ) , .IN3 ( alu[6] ) 
    , .IN4 ( n22 ) , .IN6 ( n21 ) , .IN5 ( dmem_data[6] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
AO222X1 U74 (.Q ( N24 ) , .IN2 ( imem_data[5] ) , .IN1 ( n23 ) , .IN3 ( alu[5] ) 
    , .IN4 ( n22 ) , .IN6 ( n21 ) , .IN5 ( dmem_data[5] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
AO222X1 U73 (.Q ( N23 ) , .IN2 ( imem_data[4] ) , .IN1 ( n23 ) , .IN3 ( alu[4] ) 
    , .IN4 ( n22 ) , .IN6 ( n21 ) , .IN5 ( dmem_data[4] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
AO222X1 U72 (.Q ( N22 ) , .IN2 ( imem_data[3] ) , .IN1 ( n23 ) , .IN3 ( n22 ) 
    , .IN4 ( alu[3] ) , .IN6 ( n21 ) , .IN5 ( dmem_data[3] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
AO222X1 U71 (.Q ( N21 ) , .IN2 ( imem_data[2] ) , .IN1 ( n23 ) , .IN3 ( alu[2] ) 
    , .IN4 ( n22 ) , .IN6 ( n21 ) , .IN5 ( dmem_data[2] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
AO222X1 U70 (.Q ( N20 ) , .IN2 ( imem_data[1] ) , .IN1 ( n23 ) , .IN3 ( n22 ) 
    , .IN4 ( alu[1] ) , .IN6 ( n21 ) , .IN5 ( dmem_data[1] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
AO222X1 U69 (.Q ( N19 ) , .IN2 ( imem_data[0] ) , .IN1 ( n23 ) , .IN3 ( n22 ) 
    , .IN4 ( alu[0] ) , .IN6 ( n21 ) , .IN5 ( dmem_data[0] ) , .VSS ( gnd ) 
    , .VDD ( vdd ) ) ;
AND2X1 U68 (.IN1 ( n20 ) , .IN2 ( res_sel[1] ) , .Q ( n23 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
INVX0 U67 (.ZN ( n20 ) , .VDD ( vdd ) , .INP ( res_sel[0] ) , .VSS ( gnd ) ) ;
NAND3X0 U66 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opa[2] ) , .IN3 ( n26 ) 
    , .IN2 ( n25 ) , .IN1 ( n24 ) ) ;
NAND3X0 U65 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opa[3] ) , .IN3 ( n29 ) 
    , .IN2 ( n27 ) , .IN1 ( n28 ) ) ;
AND2X1 U63 (.IN1 ( n10 ) , .IN2 ( n9 ) , .Q ( n8 ) , .VDD ( vdd ) , .VSS ( gnd ) ) ;
AND2X1 U62 (.IN1 ( n47 ) , .IN2 ( n48 ) , .Q ( n7 ) , .VDD ( vdd ) , .VSS ( gnd ) ) ;
NAND3X0 U61 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opb[4] ) , .IN3 ( n54 ) 
    , .IN2 ( n52 ) , .IN1 ( n53 ) ) ;
NAND3X0 U60 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opb[3] ) , .IN3 ( n51 ) 
    , .IN2 ( n49 ) , .IN1 ( n50 ) ) ;
NAND3X0 U59 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opb[1] ) , .IN3 ( n43 ) 
    , .IN2 ( n45 ) , .IN1 ( n44 ) ) ;
NAND3X0 U58 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opb[0] ) , .IN3 ( n40 ) 
    , .IN2 ( n42 ) , .IN1 ( n41 ) ) ;
AND2X1 U57 (.IN1 ( opb_sel[0] ) , .IN2 ( opb_sel[1] ) , .Q ( n57 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
NAND2X1 U56 (.IN2 ( n56 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( imem[4] ) 
    , .QN ( n53 ) ) ;
NAND2X1 U55 (.IN2 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( acc[4] ) 
    , .QN ( n54 ) ) ;
NAND2X1 U54 (.IN2 ( n56 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( imem[3] ) 
    , .QN ( n50 ) ) ;
NAND2X1 U53 (.IN2 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( acc[3] ) 
    , .QN ( n51 ) ) ;
NAND2X1 U52 (.IN2 ( imem[3] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n37 ) 
    , .QN ( n28 ) ) ;
NAND2X1 U51 (.IN2 ( acc[3] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n36 ) 
    , .QN ( n29 ) ) ;
NAND2X1 U50 (.IN2 ( n46 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n7 ) 
    , .QN ( opb[2] ) ) ;
NAND2X1 U49 (.IN2 ( imem[2] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n37 ) 
    , .QN ( n25 ) ) ;
NAND2X1 U48 (.IN2 ( acc[2] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n36 ) 
    , .QN ( n26 ) ) ;
NAND2X1 U47 (.IN2 ( n56 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( imem[1] ) 
    , .QN ( n44 ) ) ;
NAND2X1 U46 (.IN2 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( acc[1] ) 
    , .QN ( n45 ) ) ;
NAND2X1 U45 (.IN2 ( imem[6] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n37 ) 
    , .QN ( n34 ) ) ;
NAND2X1 U44 (.IN2 ( n57 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( pc[3] ) 
    , .QN ( n49 ) ) ;
NAND2X1 U43 (.IN2 ( pc[3] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n38 ) 
    , .QN ( n27 ) ) ;
NAND2X0 U42 (.VDD ( vdd ) , .IN1 ( n22 ) , .VSS ( gnd ) , .IN2 ( alu[7] ) 
    , .QN ( n11 ) ) ;
INVX0 U41 (.ZN ( n6 ) , .VDD ( vdd ) , .INP ( pc[2] ) , .VSS ( gnd ) ) ;
NAND2X0 U40 (.VDD ( vdd ) , .IN1 ( n11 ) , .VSS ( gnd ) , .IN2 ( n8 ) 
    , .QN ( N26 ) ) ;
NAND3X0 U38 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opa[4] ) , .IN3 ( n32 ) 
    , .IN2 ( n30 ) , .IN1 ( n31 ) ) ;
INVX0 U37 (.ZN ( n5 ) , .VDD ( vdd ) , .INP ( n57 ) , .VSS ( gnd ) ) ;
NAND3X0 U36 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opa[0] ) , .IN3 ( n14 ) 
    , .IN2 ( n12 ) , .IN1 ( n13 ) ) ;
NOR2X0 U34 (.QN ( n21 ) , .IN1 ( res_sel[1] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n20 ) ) ;
NOR2X0 U33 (.QN ( n55 ) , .IN1 ( opb_sel[0] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( opb_sel[1] ) ) ;
NOR2X0 U32 (.QN ( n56 ) , .IN1 ( opb_sel[1] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n39 ) ) ;
NAND3X0 U31 (.VDD ( vdd ) , .VSS ( gnd ) , .QN ( opa[6] ) , .IN3 ( n35 ) 
    , .IN2 ( n33 ) , .IN1 ( n34 ) ) ;
NAND2X1 U30 (.IN2 ( acc[6] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n36 ) 
    , .QN ( n35 ) ) ;
NAND2X1 U29 (.IN2 ( n56 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( imem[0] ) 
    , .QN ( n41 ) ) ;
NAND2X1 U28 (.IN2 ( n57 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( pc[0] ) 
    , .QN ( n40 ) ) ;
NAND2X1 U27 (.IN2 ( pc[6] ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( n38 ) 
    , .QN ( n33 ) ) ;
NAND2X1 U25 (.IN2 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( acc[0] ) 
    , .QN ( n42 ) ) ;
NAND2X1 U24 (.IN2 ( n21 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( dmem_data[7] ) 
    , .QN ( n10 ) ) ;
NAND2X1 U23 (.IN2 ( n57 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( pc[4] ) 
    , .QN ( n52 ) ) ;
NAND2X1 U21 (.IN2 ( n23 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( imem_data[7] ) 
    , .QN ( n9 ) ) ;
NAND2X1 U20 (.IN2 ( n55 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( acc[2] ) 
    , .QN ( n48 ) ) ;
NAND2X0 U19 (.VDD ( vdd ) , .IN1 ( n36 ) , .VSS ( gnd ) , .IN2 ( acc[4] ) 
    , .QN ( n32 ) ) ;
NAND2X0 U18 (.VDD ( vdd ) , .IN1 ( acc[0] ) , .VSS ( gnd ) , .IN2 ( n36 ) 
    , .QN ( n13 ) ) ;
NAND2X0 U17 (.VDD ( vdd ) , .IN1 ( imem[0] ) , .VSS ( gnd ) , .IN2 ( n37 ) 
    , .QN ( n12 ) ) ;
NAND2X0 U16 (.VDD ( vdd ) , .IN1 ( n37 ) , .VSS ( gnd ) , .IN2 ( imem[4] ) 
    , .QN ( n31 ) ) ;
NAND2X1 U15 (.IN2 ( n56 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( imem[2] ) 
    , .QN ( n47 ) ) ;
NAND2X0 U14 (.VDD ( vdd ) , .IN1 ( pc[0] ) , .VSS ( gnd ) , .IN2 ( n38 ) 
    , .QN ( n14 ) ) ;
endmodule




module mcu (rst , clk , dmem_update , dmem_write , imem_update , 
    opcode_update , opcode , psr_update , psr , res_update , res_sel , 
    alu_operation , alu_opa_sel , alu_opb_sel , pc_count_BAR , pc_load , 
    vdd , gnd );
input  rst ;
input  clk ;
output dmem_update ;
output dmem_write ;
output imem_update ;
output opcode_update ;
input  [7:0] opcode ;
output psr_update ;
input  [2:0] psr ;
output res_update ;
output [1:0] res_sel ;
output [3:0] alu_operation ;
output [1:0] alu_opa_sel ;
output [1:0] alu_opb_sel ;
output pc_count_BAR ;
output pc_load ;
input  vdd ;
input  gnd ;

supply1 vdd ;
supply0 gnd ;


assign imem_update = pc_count_BAR ;
IBUFFX4 INVX0_G1B1I1 (.INP ( clk_G1B1I1 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .ZN ( clk_G1B2I1 ) ) ;
INVX0 INVX0_G1B3I1 (.ZN ( clk_G1B1I1 ) , .VDD ( vdd ) , .INP ( clk ) 
    , .VSS ( gnd ) ) ;
OA21X1 U47 (.IN2 ( n30 ) , .IN3 ( n42 ) , .VSS ( gnd ) , .IN1 ( n31 ) 
    , .VDD ( vdd ) , .Q ( psr_update ) ) ;
AO222X1 U46 (.Q ( n26 ) , .IN2 ( n23 ) , .IN1 ( n24 ) , .IN3 ( n24 ) 
    , .IN4 ( psr[1] ) , .IN6 ( psr[0] ) , .IN5 ( n23 ) , .VSS ( gnd ) , .VDD ( vdd ) ) ;
OA21X1 U45 (.IN2 ( n15 ) , .IN3 ( n25 ) , .VSS ( gnd ) , .IN1 ( n31 ) 
    , .VDD ( vdd ) , .Q ( res_update ) ) ;
INVX0 U44 (.ZN ( n23 ) , .VDD ( vdd ) , .INP ( opcode[1] ) , .VSS ( gnd ) ) ;
NOR3X0 U43 (.IN2 ( opcode[4] ) , .QN ( n29 ) , .VSS ( gnd ) , .VDD ( vdd ) 
    , .IN1 ( opcode[3] ) , .IN3 ( opcode[5] ) ) ;
NOR3X0 U42 (.IN2 ( N105 ) , .QN ( n13 ) , .VSS ( gnd ) , .VDD ( vdd ) 
    , .IN1 ( n12 ) , .IN3 ( n31 ) ) ;
NOR2X0 U41 (.QN ( n12 ) , .IN1 ( n18 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n11 ) ) ;
AND3X1 U40 (.IN2 ( opcode[0] ) , .IN1 ( opcode[1] ) , .IN3 ( n3 ) , .Q ( n21 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
OR2X1 U39 (.VDD ( vdd ) , .IN2 ( n10 ) , .IN1 ( N105 ) , .VSS ( gnd ) 
    , .Q ( N104 ) ) ;
OR2X1 U38 (.VDD ( vdd ) , .IN2 ( n9 ) , .IN1 ( n17 ) , .VSS ( gnd ) 
    , .Q ( alu_operation[3] ) ) ;
AND3X1 U37 (.IN2 ( n3 ) , .IN1 ( n14 ) , .IN3 ( n23 ) , .Q ( n15 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
NOR2X0 U36 (.QN ( N123 ) , .IN1 ( n13 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n7 ) ) ;
AND2X1 U35 (.IN1 ( opcode[0] ) , .IN2 ( n15 ) , .Q ( n43 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
AND3X1 U34 (.IN2 ( n21 ) , .IN1 ( n22 ) , .IN3 ( psr[2] ) , .Q ( n27 ) 
    , .VDD ( vdd ) , .VSS ( gnd ) ) ;
OA221X1 U33 (.IN2 ( N105 ) , .IN4 ( n26 ) , .VDD ( vdd ) , .Q ( pc_load ) 
    , .IN5 ( n25 ) , .IN1 ( n27 ) , .IN3 ( n27 ) , .VSS ( gnd ) ) ;
AND2X1 U32 (.IN1 ( n15 ) , .IN2 ( n24 ) , .Q ( N30 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
AND2X1 U31 (.IN1 ( n3 ) , .IN2 ( n31 ) , .Q ( N107 ) , .VDD ( vdd ) 
    , .VSS ( gnd ) ) ;
NAND2X1 U30 (.IN2 ( opcode[7] ) , .VSS ( gnd ) , .VDD ( vdd ) 
    , .IN1 ( opcode[6] ) , .QN ( n16 ) ) ;
NOR2X0 U29 (.QN ( n17 ) , .IN1 ( n16 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n3 ) ) ;
NOR2X0 U28 (.QN ( n19 ) , .IN1 ( n17 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n7 ) ) ;
NAND2X1 U27 (.IN2 ( n19 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( opcode[6] ) 
    , .QN ( alu_operation[2] ) ) ;
INVX0 U26 (.ZN ( n22 ) , .VDD ( vdd ) , .INP ( n16 ) , .VSS ( gnd ) ) ;
NOR2X0 U25 (.QN ( n31 ) , .IN1 ( n22 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n14 ) ) ;
INVX0 U24 (.ZN ( n18 ) , .VDD ( vdd ) , .INP ( n14 ) , .VSS ( gnd ) ) ;
INVX0 U23 (.ZN ( n7 ) , .VDD ( vdd ) , .INP ( n25 ) , .VSS ( gnd ) ) ;
NOR2X0 U21 (.QN ( pc_count_BAR ) , .IN1 ( opcode_update ) , .VDD ( vdd ) 
    , .VSS ( gnd ) , .IN2 ( state_0_ ) ) ;
NOR2X0 U20 (.QN ( n42 ) , .IN1 ( opcode_update ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n6 ) ) ;
NOR2X0 U18 (.QN ( N105 ) , .IN1 ( opcode[2] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n16 ) ) ;
NOR2X1 U17 (.QN ( dmem_write ) , .IN1 ( n20 ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n7 ) ) ;
NOR2X0 U16 (.QN ( n14 ) , .IN1 ( opcode[6] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( opcode[7] ) ) ;
INVX0 U15 (.ZN ( n24 ) , .VDD ( vdd ) , .INP ( opcode[0] ) , .VSS ( gnd ) ) ;
NOR2X0 U14 (.QN ( n10 ) , .IN1 ( opcode[0] ) , .VDD ( vdd ) , .VSS ( gnd ) 
    , .IN2 ( n20 ) ) ;
NAND2X1 U13 (.IN2 ( n3 ) , .VSS ( gnd ) , .VDD ( vdd ) , .IN1 ( opcode[1] ) 
    , .QN ( n11 ) ) ;
NAND2X0 U12 (.VDD ( vdd ) , .IN1 ( n29 ) , .VSS ( gnd ) , .IN2 ( n3 ) 
    , .QN ( n30 ) ) ;
NAND3X0 U11 (.VDD ( vdd ) , .IN2 ( opcode[1] ) , .IN3 ( n3 ) , .VSS ( gnd ) 
    , .IN1 ( n14 ) , .QN ( n20 ) ) ;
INVX0 U10 (.ZN ( n3 ) , .VDD ( vdd ) , .INP ( opcode[2] ) , .VSS ( gnd ) ) ;
AO21X1 U8 (.IN2 ( opcode[0] ) , .Q ( alu_operation[0] ) 
    , .IN3 ( alu_operation[3] ) , .VSS ( gnd ) , .IN1 ( n31 ) , .VDD ( vdd ) ) ;
NAND2X0 U7 (.VDD ( vdd ) , .IN1 ( n18 ) , .VSS ( gnd ) , .IN2 ( n25 ) 
    , .QN ( n9 ) ) ;
AO21X1 U6 (.VDD ( vdd ) , .IN2 ( opcode[1] ) , .IN1 ( n31 ) 
    , .IN3 ( alu_operation[3] ) , .Q ( alu_operation[1] ) , .VSS ( gnd ) ) ;
AO21X1 U5 (.VDD ( vdd ) , .IN2 ( n31 ) , .IN1 ( opcode[2] ) , .IN3 ( n2 ) 
    , .Q ( N106 ) , .VSS ( gnd ) ) ;
AO21X1 U4 (.VDD ( vdd ) , .IN2 ( n14 ) , .IN1 ( n21 ) , .IN3 ( N105 ) , .Q ( n2 ) 
    , .VSS ( gnd ) ) ;
AND2X1 U3 (.IN1 ( n42 ) , .IN2 ( n29 ) , .Q ( n25 ) , .VDD ( vdd ) , .VSS ( gnd ) ) ;
LATCHX1 res_sel_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .D ( N30 ) 
    , .CLK ( res_update ) , .Q ( res_sel[0] ) ) ;
LATCHX1 res_sel_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .D ( n43 ) 
    , .CLK ( res_update ) , .Q ( res_sel[1] ) ) ;
LATCHX1 alu_opb_sel_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .D ( N106 ) 
    , .CLK ( N123 ) , .Q ( alu_opb_sel[0] ) ) ;
LATCHX1 alu_opb_sel_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .D ( N107 ) 
    , .CLK ( N123 ) , .Q ( alu_opb_sel[1] ) ) ;
LATCHX1 alu_opa_sel_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .D ( N104 ) 
    , .CLK ( N123 ) , .Q ( alu_opa_sel[0] ) ) ;
LATCHX1 alu_opa_sel_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .D ( N105 ) 
    , .CLK ( N123 ) , .Q ( alu_opa_sel[1] ) ) ;
DFFASX1 state_reg_1_ (.VDD ( vdd ) , .VSS ( gnd ) , .SETB ( rst ) 
    , .Q ( opcode_update ) , .CLK ( clk_G1B2I1 ) , .D ( n42 ) ) ;
DFFASX1 state_reg_0_ (.VDD ( vdd ) , .VSS ( gnd ) , .SETB ( rst ) , .QN ( n6 ) 
    , .Q ( state_0_ ) , .CLK ( clk_G1B2I1 ) , .D ( pc_count_BAR ) ) ;
endmodule




module cpu (rst , clk , imem_data , imem_addr , dmem_port_write , 
    dmem_port_value , dmem_port_addr , vdd , gnd );
input  rst ;
input  clk ;
input  [7:0] imem_data ;
output [7:0] imem_addr ;
output dmem_port_write ;
inout  [7:0] dmem_port_value ;
output [7:0] dmem_port_addr ;
inout  vdd ;
inout  gnd ;

supply1 vdd ;
supply0 gnd ;
wire [7:1] opb ;
wire [7:0] dmem_data ;
wire [7:0] alu_result ;
wire [3:0] alu_operation ;
wire [7:0] opa ;
wire [2:0] psr ;
wire [2:0] apsr ;
wire [7:0] opcode ;
wire [1:0] res_sel ;
wire [1:0] opa_sel ;
wire [1:0] opb_sel ;



ram_port ram_port (.drive_enable ( dmem_port_write ) , 
    .drive_value ( {opb[7] , opb[6] , opb[5] , opb[4] , opb[3] , opb[2] , opb[1] , 
	n3 } ) , 
    .current_value ( dmem_data ) , .port_value ( dmem_port_value ) , 
    .current_addr ( alu_result ) , .port_addr ( dmem_port_addr ) , .vdd ( vdd ) , 
    .gnd ( gnd ) ) ;


alu alu (.operation ( alu_operation ) , 
    .a_i ( {opa[7] , opa[6] , opa[5] , opa[4] , opa[3] , opa[2] , n1 , 
	opa[0] } ) , 
    .b_i ( {opb[7] , opb[6] , opb[5] , opb[4] , opb[3] , opb[2] , opb[1] , 
	n3 } ) , 
    .psr ( psr ) , .result ( alu_result ) , .apsr ( apsr ) , .vdd ( vdd ) , 
    .gnd ( gnd ) ) ;


pc pc (.rst ( n7 ) , .clk ( clk ) , .count_BAR ( pc_count ) , 
    .load ( pc_load ) , .addr_in ( alu_result ) , .addr_out ( imem_addr ) , 
    .vdd ( vdd ) , .gnd ( gnd ) ) ;


regs regs (.rst ( n7 ) , .clk ( clk ) , .dmem_update ( gnd ) , 
    .dmem_data ( dmem_data ) , .imem_update ( imem_update ) , 
    .imem_data ( imem_data ) , .opcode_update ( opcode_update ) , 
    .opcode ( {opcode[7] , n2 , opcode[5] , opcode[4] , opcode[3] , n4 , 
	opcode[1] , opcode[0] } ) , 
    .psr_update ( psr_update ) , .apsr ( apsr ) , .psr ( psr ) , 
    .res_update ( res_update ) , .res_sel ( res_sel ) , .alu ( alu_result ) , 
    .opa_sel ( opa_sel ) , .opb_sel ( opb_sel ) , 
    .opa ( {opa[7] , opa[6] , opa[5] , opa[4] , opa[3] , opa[2] , n1 , 
	opa[0] } ) , 
    .opb ( {opb[7] , opb[6] , opb[5] , opb[4] , opb[3] , opb[2] , opb[1] , 
	n3 } ) , 
    .pc ( imem_addr ) , .vdd ( vdd ) , .gnd ( gnd ) , .IN0 ( n6 ) ) ;


mcu mcu (.rst ( n6 ) , .clk ( clk ) , .dmem_write ( dmem_port_write ) , 
    .imem_update ( imem_update ) , .opcode_update ( opcode_update ) , 
    .opcode ( {opcode[7] , n2 , opcode[5] , opcode[4] , opcode[3] , n4 , 
	opcode[1] , opcode[0] } ) , 
    .psr_update ( psr_update ) , .psr ( psr ) , .res_update ( res_update ) , 
    .res_sel ( res_sel ) , .alu_operation ( alu_operation ) , 
    .alu_opa_sel ( opa_sel ) , .alu_opb_sel ( opb_sel ) , 
    .pc_count_BAR ( pc_count ) , .pc_load ( pc_load ) , .vdd ( vdd ) , 
    .gnd ( gnd ) ) ;

INVX2 U1 (.VDD ( vdd ) , .INP ( rst ) , .VSS ( gnd ) , .ZN ( n6 ) ) ;
INVX2 U2 (.VDD ( vdd ) , .INP ( rst ) , .VSS ( gnd ) , .ZN ( n7 ) ) ;
endmodule


