set tech                   ""
set max_lib                ""
set min_lib                ""
set typ_lib                ""
set tech_lef               ""
set macros_lef             ""
set mems_lef               ""
set max_lib_name           ""
set min_lib_name           ""
set cap_table              ""
set qrc_tech               ""
set cdb_slow               ""
set cdb_fast               ""
set lefdef_layermap        ""
set top_level              ""
set voltage                
set verilog_cell_models    ""
set external_driving_cell  ""
